apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  # type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
  selector:
    app: {{ .Values.metadata.name }}
